### ISSUE TITLE
Failed to run the web cam video demo, Reason: image not found?

### ISSUE THREAD

**Issue by tianqig** [shoeffner/cvloop#19]
I installed cvloop with the conda install as suggested, no errors, but when I tried to run the following demo:
` from cvloop import cvloop
cvloop()`

BTW, my computer is a Mac OS X; 10.11.4.
Got the following errors:

ImportError                               Traceback (most recent call last)
<ipython-input-1-26cc95f018d8> in <module>()
----> 1 from cvloop import cvloop
      2 
      3 cvloop()
      4 

~/anaconda/envs/py36/lib/python3.6/site-packages/cvloop/__init__.py in <module>()
     10 
     11 try:
---> 12     import cv2
     13     OPENCV_FOUND = True
     14 except ModuleNotFoundError:

ImportError: dlopen(/Users/david/anaconda/envs/py36/lib/python3.6/site-packages/cv2.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libopenblasp-r0.2.19.dylib
  Referenced from: /Users/david/anaconda/envs/py36/lib/libopencv_hdf.3.2.0.dylib

  **Reason: image not found**
=======================================================
opencv:             3.2.0-np112py36_0 conda-forge, was installed when installing cvloop

When I tried to play a video file, got the same error: **image not found.**

Please help

Thanks

**Comment by tianqig** [comment]
I  found the problem was caused by OpenCV installation when installing cvloop:
opencv:             3.2.0-np112py36_0 conda-forge

No errors were reported, but something is wrong, I can't import it from Python, got the same error message.

**Comment by AndreaSuckro** [comment]
I reproduced your error - it seems related to this issue: https://github.com/conda-forge/opencv-feedstock/issues/64

`conda install -c conda-forge numpy` fixed it for me :) Hope that helps!

**Comment by AndreaSuckro** [comment]
Please reopen if the issue persists.
