### ISSUE TITLE
Provide configurable and default paths to OpenCV example files

### ISSUE THREAD

**Issue by shoeffner** [shoeffner/cvloop#8]
Provide paths to OpenCV files like the haarcascades.

On MacOS with brew this seems to be:

`/usr/local/opt/opencv3/share/OpenCV`

On Linux (Arch, thanks @ahoereth) this seems to be:

`/usr/share/opencv`

**Comment by AndreaSuckro** [comment]
On linux ubuntu it is also `/usr/share/opencv/`and on my mac it's `/usr/local/Cellar/opencv3/HEAD-a85b4b5/share/OpenCV`

**Comment by shoeffner** [comment]
You should find a link in `/usr/local/opt/opencv3` which points to your Cellar installation, e.g.:

```
ls -l /usr/local/opt/opencv3 
/usr/local/opt/opencv3 -> ../Cellar/opencv3/HEAD-a85b4b5
```

Do you mind checking that?
If it's not there, try `brew link opencv3`.
